[CORE-11976] Use session context properties for interop session identification
corda/corda-api pull request #1013
Opened 2023-03-29 10:23 UTC by ac101m

# Changes
- Bump interop api revision to 2
- Add `isInteropSession` field to flow mapper state avro schema (with default value of false).

2023-04-04 12:45 UTC, yarivus approved these changes
LGTM

2023-04-05 10:21 UTC, SaurabhR3 requested changes

2023-04-05 10:21 UTC, SaurabhR3 commented on gradle.properties
> +cordaApiRevision = 3
Need to bump up the version to 5, I just increased to to 4 for synching up with release branch.

2023-04-05 10:32 UTC, ac101m commented on gradle.properties
> +cordaApiRevision = 3
The version will be incremented when I resolve conflicts before merging and once the other changes in the PR are approved, as per the process detailed here: https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4281270286/TL+DR+Rules+for+merging+breaking+API+changes+in+Corda+5
I'll just post in ledger ops rather than the main version locking thread.

2023-04-05 10:56 UTC, jmacmahonr3 approved these changes
Looks grand, but the sooner we document any potential redesigns the better

2023-04-05 11:08 UTC, ac101m commented
> Looks grand, but the sooner we document any potential redesigns the better

I think the plan for now is to stick with the session based mechanism for the time being as it's mostly complete and a redesign would still involve a few unknowns.

2023-04-05 14:11 UTC, merged

2023-04-06 09:39 UTC, yarivus reviewed
thx @ac101m