CORE-10453 : Interfaces for alias identity look up
corda/corda-api pull request #1096
Opened 2023-05-04 16:57 UTC by SaurabhR3

Added interfaces for alias identity look up

2023-05-04 19:43 UTC, yarivus requested changes

2023-05-04 19:43 UTC, yarivus commented on interop/src/main/java/net/corda/v5/interop/AliasMemberInfo.java
> +public interface AliasMemberInfo {
```suggestion
import net.corda.v5.base.annotations.CordaSerializable;
import org.jetbrains.annotations.NotNull;
import java.util.List;

@CordaSerializable
public interface AliasMemberInfo {
```

2023-05-04 19:43 UTC, yarivus commented on interop/src/main/java/net/corda/v5/interop/HoldingIdAliasGroupInfo.java
> +import java.util.List;
```suggestion
import net.corda.v5.base.annotations.CordaSerializable;
import java.util.List;
```

2023-05-05 09:19 UTC, SaurabhR3 commented on interop/src/main/java/net/corda/v5/interop/AliasMemberInfo.java
> +public interface AliasMemberInfo {
Fixed in 730895f

2023-05-05 09:19 UTC, SaurabhR3 commented on interop/src/main/java/net/corda/v5/interop/HoldingIdAliasGroupInfo.java
> +import java.util.List;
Fixed in 730895f

2023-05-05 09:59 UTC, yarivus approved these changes
LGTM

2023-05-05 09:59 UTC, szymonsztuka requested changes
This PR anyway needs to wait before merging for a matching PR in `corda-runtime-os`  using these interfaces (I mean they will be reviewed together).

2023-05-05 09:59 UTC, szymonsztuka commented on interop/src/test/java/net/corda/v5/interop/HoldingIdAliasGroupInfoTest.java
> +    void getShortHash() {
Those tests test Mockito framework, the don't test the code business logic, please remove the whole class.

2023-05-05 09:59 UTC, szymonsztuka commented on interop/src/main/java/net/corda/v5/interop/AliasMemberInfo.java
> +public interface AliasMemberInfo {
None of the interfaces has any JavaDoc !

2023-05-15 13:59 UTC, closed without merging