Replace RemoteAliasLookUp with InteropIdentityLookup
corda/corda-api pull request #1136
Opened 2023-05-29 16:39 UTC by jmacmahonr3

An alternative more simplistic implementation of the InterOp equivalent of the MemberLookup. 

What's noteworthy about this new API is that the Application name is the sole identifier an the flow level.

2023-05-29 17:04 UTC, yarivus requested changes

2023-05-29 17:04 UTC, yarivus commented on interop/src/main/java/net/corda/v5/interop/InterOpIdentityInfo.java
> +     * @return The {@link String} of the Identities X500.
```suggestion
     * @return The {@link String} of the Identity's X500.
```

2023-05-30 08:16 UTC, yarivus approved these changes
LGTM

2023-05-30 09:24 UTC, szymonsztuka reviewed
Needs to increment API version in gradle.properties.

2023-05-30 09:24 UTC, szymonsztuka commented on interop/src/main/java/net/corda/v5/interop/InterOpIdentityInfo.java
> +
Remove a new line

2023-05-30 09:24 UTC, szymonsztuka commented on interop/src/main/java/net/corda/v5/interop/InterOpIdentityInfo.java
> + * <p>This interface represents the alias member details like Application Name, facadeIds etc.
Very minor - I think we can remove "< p >" and extra empty line in that Javadoc

2023-05-30 09:24 UTC, szymonsztuka commented on application/src/main/java/net/corda/v5/application/interop/InteropIdentityLookUp.java
> + * <p>This interface represents the injectable service for client corDapp to look up the remote alias identity.
We would need to clearly separate this service from any services returning normal member group, i would use explicit words like _Interoperability group_ etc. Also javadoc for other services doesn't mention `injectable`, all Corda API services are injectable.
Maybe something like that, which explicitly shows the different with existing `memberLookup`:
``The service allows a flow to retrieve alter-ego members from other networks, which are register in the holding identity's interoperability group.``

2023-05-30 09:24 UTC, szymonsztuka commented on interop/src/main/java/net/corda/v5/interop/InterOpIdentityInfo.java
> + * <p>This interface represents the alias member details like Application Name, facadeIds etc.
Maybe a bit later not for this PR/ so just suggestion, but the description doesn't match the interface name or doesn't refer: "Identity" or "InteroOp",  how "alias member" relates to "InterOpIdentity"?

2023-05-30 09:24 UTC, szymonsztuka commented on application/src/main/java/net/corda/v5/application/interop/InteropIdentityLookUp.java
> +     * @return The {@link List< InterOpIdentityInfo >} representing the alias member info for given facadeId.
Remove spaces after `<` and before `>`

2023-05-30 09:24 UTC, szymonsztuka commented on application/src/main/java/net/corda/v5/application/interop/InteropIdentityLookUp.java
> +     * @return The {@link InterOpIdentityInfo} representing the alias member info for given alias x500name and host network.
This is a crucial parameter and it's not described, is this intentional?  
What is `applicationName`, how does it relates to  "x500name" and "host network".?

2023-05-30 11:28 UTC, jmacmahonr3 commented on application/src/main/java/net/corda/v5/application/interop/InteropIdentityLookUp.java
> + * <p>This interface represents the injectable service for client corDapp to look up the remote alias identity.
Please check updated docs

2023-05-30 14:59 UTC, yarivus approved these changes
LGTM

2023-05-31 10:43 UTC, szymonsztuka approved these changes
Approving, the `cordaApiRevision` probably should be `7` and not `8`, but doesn't really matter.

2023-05-31 13:02 UTC, merged