ES-96/SBOM generation
corda/corda-api pull request #1152
Opened 2023-06-19 13:46 UTC by seanbrereton

Creating SBOM using the cyclonedx plugin.
Adding a task to zip the sboms into 1 folder and publish them.
Tested locally: https://gradle.dev.r3.com/s/zomuydafgew2e

2023-06-19 13:48 UTC, yarivus submitted a review, later dismissed
LGTM

2023-06-19 13:52 UTC, yarivus reviewed
sorry I missed the typo ;)

2023-06-20 08:56 UTC, ronanbrowne requested changes
minor comment re version

2023-06-20 08:56 UTC, ronanbrowne commented on settings.gradle
> +        id "org.cyclonedx.bom" version "1.7.4"
Can we externalize this property to gradle.properties file in line with others above this

2023-06-20 12:03 UTC, ronanbrowne approved these changes
LGTM

2023-06-20 12:21 UTC, yarivus approved these changes
LGTM

2023-06-20 12:23 UTC, merged