CORE-14023 ledger transaction resolve states
corda/corda-api pull request #1193
Opened 2023-07-28 17:43 UTC by lankydan

Changes to support retrieving a ledger transaction in one step, including resolving the input and reference states of the transaction and retrieving the transaction's signatures.

2023-07-31 10:09 UTC, simon-johnson-r3 requested changes

2023-07-31 10:09 UTC, simon-johnson-r3 commented on data/avro-schema/src/test/kotlin/net/corda/data/ledger/persistence/LedgerPersistenceRequestSchemaCompatibilityTest.kt
> +    fun `check SimpleMessage schema changes between Corda 5_0 and 5_1 are compatible`() {
c+p error: `SimpleMessage` should be `LedgerPersistenceRequest`

2023-07-31 10:30 UTC, simon-johnson-r3 approved these changes, later dismissed

2023-07-31 13:57 UTC, vlajos submitted a review, later dismissed

2023-08-02 08:36 UTC, vlajos approved these changes

2023-08-02 08:45 UTC, driessamyn approved these changes
LGTM

2023-08-02 08:48 UTC, merged