DA5-15 Recurring merge from main
corda/corda-api pull request #1317
Opened 2023-10-25 16:22 UTC by ac101m

# Changes
- Bump API version to 25
- Merge changes from release/os/5.1

# Notes
- Deprecation in ledger API will need to be addressed at a later date

2023-10-25 16:23 UTC, szymonsztuka approved these changes

2023-10-26 08:55 UTC, vlajos approved these changes

2023-10-26 09:00 UTC, ronanbrowne requested changes

2023-10-26 09:00 UTC, ronanbrowne commented on .github/CODEOWNERS
> -# Build scripts and Jenkins files should be audited by BLT
this was for the code freeze on 5.1 you probably don't want to take this into your branch

2023-10-27 12:49 UTC, ac101m commented
Closed due to flow worker team reverting topology changes

2023-10-27 12:49 UTC, closed without merging