CORE-6717 Add schemas for hosted identity reconciliation
corda/corda-api pull request #1620
Opened 2024-04-24 10:47 UTC by YashNabar

2024-04-24 13:26 UTC, nikinagy commented on data/avro-schema/src/main/resources/avro/net/corda/data/p2p/HostedIdentityEntry.avsc
> +      "type": ["null", "int"],
add docs?

2024-04-29 14:50 UTC, nikinagy approved these changes, later dismissed
LGTM

2024-04-30 10:03 UTC, owenstanford approved these changes, later dismissed

2024-04-30 10:26 UTC, driessamyn requested changes, later dismissed
This cannot go in 5.2 as patch releases must be able to be applied in place (without an upgrade process for DBs etc).

2024-04-30 10:33 UTC, nikinagy commented
> This cannot go in 5.2 as patch releases must be able to be applied in place (without an upgrade process for DBs etc).

@driessamyn The main problem is that we were not persisting data in the DB, so in case of kafka data loss we lost everything.
The hosted identities topic was never backed up by any sort of DB entity. Hence we had no DB reconciliation in place.
I don't see how we could fix the SBI issue for clients without making any changes to the DB. Especially, since the main issue is that we are missing persistence for this data.

2024-05-01 10:40 UTC, simon-johnson-r3 commented on data/config-schema/src/main/resources/net/corda/schema/configuration/reconciliation/1.0/corda.reconciliation.json
> +    },
Just a heads up, after upgrade it's possible the config read by a worker will not yet have this property with a default propagated to it. The code must be able to handle this property is missing in 5.2.1. See https://r3-cev.atlassian.net/wiki/spaces/CB/pages/4564091182/Making+a+Config+Change for more details.

2024-05-09 09:38 UTC, simon-johnson-r3 approved these changes

2024-05-09 10:52 UTC, conalsmith-r3 approved these changes
LGTM

2024-05-09 11:01 UTC, merged