CORE-5338: add FindWithNamedQuery.avsc
corda/corda-api pull request #482
Opened 2022-07-19 21:58 UTC by dickon

CORE-5338: add a simple FindWithNamedQuery message for the persistence API

2022-07-20 09:43 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +      "doc": "the name of a named query defined somewhere in the virtual node"
```suggestion
      "doc": "The name of a named query defined in the CPK."
```

2022-07-20 09:44 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +      "doc": "parameters for the query"
```suggestion
      "doc": "Parameters for the query. Value can be a complex type and is an AMQP serialised payload."
```

2022-07-20 09:44 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +        "values": "bytes"
I think we said this should be `bytes` or `null` as null is a valid paramater in a JPA query.

2022-07-20 09:45 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +  "name": "FindWithNamedQuery",
I think it's worth adding the offset and limit parameters too. I know we have 2 JIRAs splitting it up, but adding them now will avoid another API change that then needs a version bump.

2022-07-21 16:11 UTC, driessamyn requested changes
Sorry, bit nitpicky about the documentation, but I think it's important style is consistent with other schemas a we may be generating documentation from them.

I realise that some others in this directory are also not consistent, but I will try to fix that up with a separate PR.

2022-07-21 16:11 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +       "doc": "offset into the query results"
Brought the language in line with the public API:

```suggestion
       "doc": "The index of the first result in the query to return."
```

2022-07-21 16:11 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +      "doc": "parameters for the query, with each value represented as a bytes array payload serialized in AMQP format"
```suggestion
      "doc": "Parameters for the query, with each value represented as a bytes array payload serialized in AMQP format."
```

2022-07-21 16:11 UTC, driessamyn commented on data/avro-schema/src/main/resources/avro/net/corda/data/persistence/FIndWithNamedQuery.avsc
> +        "doc": "limit number of query results; 0 for no limit"
The public API says Int.Max is the default, so I don't think we should say 0 is a limit here. I think it's ok for it to be a mandatory property in our internal API and we'll take whatever is passed in. (So `0` would mean don't return anything).

Also brought the language in line with the public API.

```suggestion
        "doc": "Maximum number of results to return."
```

2022-07-25 07:27 UTC, driessamyn submitted a review, later dismissed
LGTM

2022-07-25 09:21 UTC, lankydan approved these changes, later dismissed

2022-07-25 16:53 UTC, driessamyn approved these changes
LGTM

2022-07-25 16:54 UTC, merged