CORE-6703 Merkletree specific KDoc updates
corda/corda-api pull request #574
Opened 2022-09-14 10:50 UTC by vlajos

Merkle tree specific KDoc updates.

2022-09-14 11:27 UTC, nadinequinr3 requested changes
@vlajos I've added a couple of edits. From a Tech Writing perspective, everything else looks ok but it would be worth you reviewing again to make sure a CorDapp Developer has all of the information they would need to use any element. Thanks.

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> + *  - Base Digest Algorithm.
```suggestion
 *  - Base Digest Algorithm
```

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> +     * @param index the leaf's index.
```suggestion
     * @param index The leaf's index.
```

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> +     * @param index the leaf's index.
```suggestion
     * @param index The leaf's index.
```

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> +     * @param nonce the leaf's nonce.
```suggestion
     * @param nonce The leaf's nonce.
```

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> +     * @param bytes the leaf's content bytes.
```suggestion
     * @param bytes The leaf's content bytes.
```

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> +     * @param leaves the tree's leaves.
```suggestion
     * @param leaves The tree's leaves.
```

2022-09-14 11:27 UTC, nadinequinr3 commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTree.kt
>      val root: SecureHash
"@property leaves are the input data elements. Usually the hashes of something larger deterministically serialized."
(line 13)
Suggest:
The input data...

2022-09-14 13:14 UTC, nadinequinr3 submitted a review, later dismissed
LGTM

2022-09-15 10:34 UTC, mnesbit commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleProof.kt
> +     * Checks if the [MerkleProof] has been generated from a [MerkleTree] with the given [root].
Should have @Param and @Returns info

2022-09-15 10:37 UTC, mnesbit commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTree.kt
> +     * @property leaves The input data elements. Usually the hashes of something larger deterministically serialized.
In practice these are actually serialized objects not hashes in our current data model

2022-09-15 10:42 UTC, mnesbit commented on crypto/src/main/kotlin/net/corda/v5/crypto/merkle/MerkleTreeHashDigestProvider.kt
> +     * Returns a size proof.
perhaps expand a bit.
Returns a size proof that reveals the number of leaves in the Merkle tree, but not the content of the leaves.

2022-09-15 12:32 UTC, mnesbit approved these changes
OK

2022-09-15 12:34 UTC, merged