NOTICK: javadocJar depends on assemble task
corda/corda-api pull request #749
Opened 2022-12-17 12:58 UTC by ronanbrowne

add javadoc generation to assemble task to prevent the need for a separate dedicated target to be called in the CI in a effort to reduce build times (less gradle stages = less configuration overhead if we can do the work in one stage) , ./gradlew build or assemble will now produce this java doc.

`generateJavaDocWithBuild` property must be present for this, property introduced as in most cases this is not required when building locally.

2022-12-24 18:37 UTC, yarivus requested changes

2022-12-24 18:37 UTC, yarivus commented on build.gradle
> +        if(project.hasProperty('generateJavaDocWithBuild')) {
fix style (indent) and spaces next to () and if

2022-12-25 23:32 UTC, chrisr3 commented on build.gradle
> +                assemble.dependsOn javadocJar
Alternatively:
```gradle
artifacts {
    archives javadocJar
}
```

2022-12-28 10:24 UTC, yarivus approved these changes
LGTM

2022-12-28 10:39 UTC, merged